// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/emrecavdar94/mars-rover/cmd/mars-rover (interfaces: IPlateau)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPlateau is a mock of IPlateau interface.
type MockIPlateau struct {
	ctrl     *gomock.Controller
	recorder *MockIPlateauMockRecorder
}

// MockIPlateauMockRecorder is the mock recorder for MockIPlateau.
type MockIPlateauMockRecorder struct {
	mock *MockIPlateau
}

// NewMockIPlateau creates a new mock instance.
func NewMockIPlateau(ctrl *gomock.Controller) *MockIPlateau {
	mock := &MockIPlateau{ctrl: ctrl}
	mock.recorder = &MockIPlateauMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPlateau) EXPECT() *MockIPlateauMockRecorder {
	return m.recorder
}

// GetPlateauSize mocks base method.
func (m *MockIPlateau) GetPlateauSize() (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlateauSize")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetPlateauSize indicates an expected call of GetPlateauSize.
func (mr *MockIPlateauMockRecorder) GetPlateauSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlateauSize", reflect.TypeOf((*MockIPlateau)(nil).GetPlateauSize))
}
